name: sitemap_monitor
description: A Flutter app to monitor sitemap.xml changes
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.4.0
  # shared_preferences: ^2.2.2
  # path_provider: ^2.1.1
  # crypto: ^3.0.3
  # pretty_diff_text: ^2.1.0
  # cupertino_icons: ^1.0.2
  xml: ^6.5.0

  # flutter_web_plugins:
  #   sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
