name: sitemap_monitor
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  sitemap_with_url:
    path: features/sitemap_with_url
  sitemap_with_sitemap:
    path: features/sitemap_with_sitemap
  sitemap_with_search:
    path: features/sitemap_with_search

dev_dependencies:
  flutter_lints: 5.0.0

flutter:
  uses-material-design: true
