name: sitemap_with_sitemap
publish_to: "none"

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.4.0
  xml: ^6.5.0

dev_dependencies:
  flutter_lints: 5.0.0

flutter:
  uses-material-design: true
